### ISSUE TITLE
Create Database and add data

### ISSUE THREAD

**Issue by M3kH** [hruy28/Final-Project-HYF#4]
The application needs a Database to store each words and provided the relative translation.

**Requirements:**
- We should support multi languages.
- We should make sure that users can submit new words and relative translations and after the Moderator approval should be able to consume in the application.

**Todo:**
- [ ] Define the structure of the DB: Tables, Columns + Data Types and add them to the Readme
- [ ] Get the data from a source (xls,json,csv or whatever) and insert in the database
- [ ] Add the data source in the git repo
- [ ] Add the relative SQL file to create the database
- [ ] Add a setup script that reads the data source and put into the database
