### ISSUE TITLE
create front end

### ISSUE THREAD

**Issue by gidesegid** [hruy28/Final-Project-HYF#5]
The application will have a user interface  which translates a word from a language to another language.

**Requirments**
- A user has to select a language.
- The user should be invited to write a word he wants to translate.
- The user has to click a button to see the word he wrote on the above.
- The user interface has to have a textbox to display the translated word.
- If something goes wrong we should display an error message.

**Todo:**
- [x] create html page.
- [x] add select box
  -[x] add input textbox
- [x] add button
- [x] add output textbox
- [ ] add a placeholder for error messages

**Comment by M3kH** [comment]
This is going in the nice direction, really cool to see progress! 👍
